### ISSUE TITLE
Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [seefo/PD2SaveEditor#2]
When running (in Powershell) `.\PD2SE.exe -i .\save098.sav -o output.sav` (with both PD2SE.exe and save098.sav (freshly copied from `%localappdata%\PAYDAY 2\saves\<steamid>\`), the following text is produced:
```
An unknown error has occured: Value cannot be null.
Parameter name: key
```
Interestingly enough, I encounter this same error when attempting to launch PayDay2SaveView (which I finally figured out how to build properly after an hour or two (there's absolutely no documentation about it on its repo, and it doesn't accept issue submissions)). Its text is more verbose though:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at PaydaySaveEditor.PD2.GameData.ReadDictionary(BinaryReader br) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PaydaySaveEditor\PD2\GameData.cs:line 115
   at PaydaySaveEditor.PD2.GameData.ReadDictionary(BinaryReader br) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PaydaySaveEditor\PD2\GameData.cs:line 118
   at PaydaySaveEditor.PD2.GameData.ReadDictionary(BinaryReader br) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PaydaySaveEditor\PD2\GameData.cs:line 118
   at PaydaySaveEditor.PD2.GameDataBlock..ctor(BinaryReader br) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PaydaySaveEditor\PD2\GameDataBlock.cs:line 18
   at PaydaySaveEditor.PD2.SaveFile..ctor(String filePath, Boolean encrypted) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PaydaySaveEditor\PD2\SaveFile.cs:line 68
   at PayDay2SaveView.Program.Main(String[] args) in C:\Users\JKPwnage\noSync\PayDay2SaveView\PayDay2SaveView\Program.cs:line 22
```
I know it's been nearly a decade since this was made, but hopefully you can give some guidance.

**Comment by walale12** [comment]
I had that issue too, I rebuilt it from source in Rider and it seems to work fine now. Hope this helps.

**Comment by capelosini** [comment]
I don't know if it's too late, but, I forked this project to try update some stuff, like adding the editor UI, i will try to solve this problem too, if it isn't already. This is the link to the fork [https://github.com/capelosini/PD2SE/](https://github.com/capelosini/PD2SE/) btw.
